# -*- coding: utf-8 -*-
"""The 7 App Store screenshot screens — using REAL app screenshots from /upload
wrapped in a premium device frame, with localized glassmorphic ASO callouts."""

from templates_base import icon, GREEN, ROSE, WHITE
import base64, os

ASSET_DIR = os.path.join(os.path.dirname(__file__), "assets", "app-ui")
_appshot_cache = {}

def appshot(name):
    if name not in _appshot_cache:
        p = os.path.join(ASSET_DIR, f"{name}.jpeg")
        with open(p, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        _appshot_cache[name] = f"data:image/jpeg;base64,{b64}"
    return _appshot_cache[name]

def _frame(img_name):
    return f'<div class="island"></div><img class="appshot" src="{appshot(img_name)}" alt="">'

def _callout(icon_name, title, sub, color, bottom=150):
    cls = "rose" if color == ROSE else "green"
    return f'<div class="callout {cls}" style="bottom:{bottom}px"><div class="ci">{icon(icon_name,44,color,2)}</div><div><div class="ct">{title}</div><div class="cs">{sub}</div></div></div>'

def _pill(icon_name, title, sub, color=GREEN):
    return f'<div class="pill"><div class="pi">{icon(icon_name,34,color,2)}</div><div><div class="pt">{title}</div><div class="ps">{sub}</div></div></div>'

CALL = {
    "en-US": {"offline_t":"Available Offline","offline_s":"Play anywhere · no Wi-Fi needed","eq_t":"10-Band Equalizer","eq_s":"Tune every beat. Boost the bass.","organize_t":"Organize Every Song","organize_s":"Albums, artists, folders & playlists","search_t":"Find Music Instantly","search_s":"Songs, artists & albums in a flash","playlist_t":"Build Your Perfect Playlist","playlist_s":"Curate & organize your collections","immersive_t":"Immersive Now Playing","immersive_s":"Full-screen artwork, lyrics & controls","p_off_t":"Offline","p_off_s":"No signal needed","p_eq_t":"Equalizer","p_eq_s":"Tune every beat","p_lyrics_t":"Lyrics","p_lyrics_s":"Sing along","p_hires_t":"Hi-Res","p_hires_s":"Lossless sound"},
    "ar": {"offline_t":"متاح دون إنترنت","offline_s":"شغّل أينما كنت · بدون Wi-Fi","eq_t":"مُعادل 10 نطاقات","eq_s":"اضبط كل نغمة. عزّز الباس.","organize_t":"نظّم كل أغنية","organize_s":"ألبومات، فنانون، مجلدات وقوائم","search_t":"اعثر فوراً","search_s":"أغاني وفنانون وألبومات بلمح البصر","playlist_t":"اصنع قائمتك المثالية","playlist_s":"نظّم ورتّب مجموعاتك","immersive_t":"تشغيل غامر","immersive_s":"غلاف كامل، كلمات وتحكّم سلس","p_off_t":"أوفلاين","p_off_s":"بدون إشارة","p_eq_t":"مُعادل","p_eq_s":"اضبط كل نغمة","p_lyrics_t":"كلمات","p_lyrics_s":"غنِّ معاً","p_hires_t":"Hi-Res","p_hires_s":"صوت بدون فقدان"},
    "de": {"offline_t":"Offline verfügbar","offline_s":"Überall hören · ohne WLAN","eq_t":"10-Band Equalizer","eq_s":"Jeden Beat stimmen. Bass boosten.","organize_t":"Jeden Song organisieren","organize_s":"Alben, Künstler, Ordner & Playlists","search_t":"Musik sofort finden","search_s":"Songs, Künstler & Alben im Blitz","playlist_t":"Deine perfekte Playlist","playlist_s":"Sammeln & sortieren — deine Sammlung","immersive_t":"Immersives Now Playing","immersive_s":"Vollbild-Cover, Lyrics & Steuerung","p_off_t":"Offline","p_off_s":"Ohne Empfang","p_eq_t":"Equalizer","p_eq_s":"Jeden Beat","p_lyrics_t":"Lyrics","p_lyrics_s":"Mitsingen","p_hires_t":"Hi-Res","p_hires_s":"Verlustfrei"},
    "fr": {"offline_t":"Disponible hors ligne","offline_s":"Écoutez partout · sans Wi-Fi","eq_t":"Égaliseur 10 bandes","eq_s":"Réglez chaque beat. Boostez les basses.","organize_t":"Organisez chaque titre","organize_s":"Albums, artistes, dossiers & playlists","search_t":"Trouvez instantanément","search_s":"Titres, artistes & albums en un éclair","playlist_t":"Votre playlist parfaite","playlist_s":"Composez & organisez vos collections","immersive_t":"Lecture immersive","immersive_s":"Pochette plein écran, paroles & contrôles","p_off_t":"Hors ligne","p_off_s":"Sans réseau","p_eq_t":"Égaliseur","p_eq_s":"Chaque beat","p_lyrics_t":"Paroles","p_lyrics_s":"Chantez","p_hires_t":"Hi-Res","p_hires_s":"Sans perte"},
    "es": {"offline_t":"Disponible sin conexión","offline_s":"Escucha donde quieras · sin Wi-Fi","eq_t":"Ecualizador de 10 bandas","eq_s":"Ajusta cada beat. Refuerza el bajo.","organize_t":"Organiza cada canción","organize_s":"Álbumes, artistas, carpetas y listas","search_t":"Encuentra al instante","search_s":"Canciones, artistas y álbumes en un flash","playlist_t":"Tu playlist perfecta","playlist_s":"Crea y organiza tus colecciones","immersive_t":"Reproducción inmersiva","immersive_s":"Carátula completa, letras y controles","p_off_t":"Sin conexión","p_off_s":"Sin señal","p_eq_t":"Ecualizador","p_eq_s":"Cada beat","p_lyrics_t":"Letras","p_lyrics_s":"Canta","p_hires_t":"Hi-Res","p_hires_s":"Sin pérdida"},
    "it": {"offline_t":"Disponibile offline","offline_s":"Ascolta ovunque · senza Wi-Fi","eq_t":"Equalizzatore 10 bande","eq_s":"Regola ogni beat. Potenzia i bassi.","organize_t":"Organizza ogni brano","organize_s":"Album, artisti, cartelle e playlist","search_t":"Trova all'istante","search_s":"Brani, artisti e album in un lampo","playlist_t":"La playlist perfetta","playlist_s":"Crea e organizza le tue collezioni","immersive_t":"Riproduzione immersiva","immersive_s":"Copertina piena, testi e controlli","p_off_t":"Offline","p_off_s":"Senza segnale","p_eq_t":"Equalizz.","p_eq_s":"Ogni beat","p_lyrics_t":"Testi","p_lyrics_s":"Canta","p_hires_t":"Hi-Res","p_hires_s":"Lossless"},
    "pt-BR": {"offline_t":"Disponível offline","offline_s":"Ouça em qualquer lugar · sem Wi-Fi","eq_t":"Equalizador de 10 bandas","eq_s":"Ajuste cada batida. Reforce o grave.","organize_t":"Organize cada música","organize_s":"Álbuns, artistas, pastas e playlists","search_t":"Encontre num instante","search_s":"Músicas, artistas e álbuns num flash","playlist_t":"Sua playlist perfeita","playlist_s":"Crie e organize suas coleções","immersive_t":"Reprodução imersiva","immersive_s":"Capa cheia, letras e controles","p_off_t":"Offline","p_off_s":"Sem sinal","p_eq_t":"Equaliz.","p_eq_s":"Cada batida","p_lyrics_t":"Letras","p_lyrics_s":"Cante","p_hires_t":"Hi-Res","p_hires_s":"Sem perdas"},
    "nl": {"offline_t":"Offline beschikbaar","offline_s":"Luister overal · zonder wifi","eq_t":"10-band Equalizer","eq_s":"Stem elke beat. Boost de bas.","organize_t":"Organiseer elk nummer","organize_s":"Albums, artiesten, mappen & playlists","search_t":"Vind direct","search_s":"Nummers, artiesten & albums in een vloek","playlist_t":"Jouw perfecte playlist","playlist_s":"Stel samen en organiseer je collectie","immersive_t":"Meeslepend Now Playing","immersive_s":"Volledig artwork, teksten & bediening","p_off_t":"Offline","p_off_s":"Zonder bereik","p_eq_t":"Equalizer","p_eq_s":"Elke beat","p_lyrics_t":"Teksten","p_lyrics_s":"Meezingen","p_hires_t":"Hi-Res","p_hires_s":"Lossless"},
    "tr": {"offline_t":"Çevrimdışı kullanılabilir","offline_s":"Her yerde dinle · Wi-Fi gerekmez","eq_t":"10 Bantlı Ekolayzer","eq_s":"Her beat'i ayarla. Bası güçlendir.","organize_t":"Her şarkıyı düzenle","organize_s":"Albümler, sanatçılar, klasörler ve listeler","search_t":"Anında bul","search_s":"Şarkı, sanatçı ve albümler göz açında","playlist_t":"Mükemmel listeni yarat","playlist_s":"Koleksiyonunu oluştur ve düzenle","immersive_t":"Etkileyici çalma ekranı","immersive_s":"Tam ekran kapak, sözler ve kontroller","p_off_t":"Çevrimdışı","p_off_s":"Sinyalsiz","p_eq_t":"Ekolayzer","p_eq_s":"Her beat","p_lyrics_t":"Sözler","p_lyrics_s":"Söyle","p_hires_t":"Hi-Res","p_hires_s":"Kayıpsız"},
    "ru": {"offline_t":"Доступно офлайн","offline_s":"Слушай везде · без Wi-Fi","eq_t":"10-полосный эквалайзер","eq_s":"Настрой каждый бит. Усиль бас.","organize_t":"Порядок в каждой песне","organize_s":"Альбомы, артисты, папки и плейлисты","search_t":"Мгновенный поиск","search_s":"Песни, артисты и альбомы вмиг","playlist_t":"Свой идеальный плейлист","playlist_s":"Собирай и упорядочивай коллекции","immersive_t":"Погружающий плеер","immersive_s":"Обложка на весь экран, тексты и управление","p_off_t":"Офлайн","p_off_s":"Без сети","p_eq_t":"Эквалайзер","p_eq_s":"Каждый бит","p_lyrics_t":"Тексты","p_lyrics_s":"Подпевай","p_hires_t":"Hi-Res","p_hires_s":"Без потерь"},
    "ja": {"offline_t":"オフラインで聴ける","offline_s":"どこでも再生 · Wi-Fi不要","eq_t":"10バンドイコライザー","eq_s":"ビートを整え、低音を強化。","organize_t":"すべての曲を整理","organize_s":"アルバム、アーティスト、フォルダ、リスト","search_t":"一瞬で検索","search_s":"曲・アーティスト・アルバムを即検索","playlist_t":"完璧なプレイリストを","playlist_s":"コレクションを作成・整理","immersive_t":"没入型の再生画面","immersive_s":"全面ジャケット、歌詞、操作","p_off_t":"オフライン","p_off_s":"圏外でも","p_eq_t":"イコライザー","p_eq_s":"ビート調整","p_lyrics_t":"歌詞","p_lyrics_s":"一緒に","p_hires_t":"ハイレゾ","p_hires_s":"ロスレス"},
    "ko": {"offline_t":"오프라인 재생","offline_s":"어디서나 재생 · Wi-Fi 불필요","eq_t":"10밴드 이퀄라이저","eq_s":"모든 비트 조정, 베이스 강화.","organize_t":"모든 곡 정리","organize_s":"앨범, 아티스트, 폴더, 재생목록","search_t":"즉시 검색","search_s":"곡·아티스트·앨범 순식간에","playlist_t":"완벽한 재생목록","playlist_s":"컬렉션을 만들고 정리하세요","immersive_t":"몰입형 재생 화면","immersive_s":"풀스크린 자켓, 가사, 조작","p_off_t":"오프라인","p_off_s":"신호 없이","p_eq_t":"이퀄라이저","p_eq_s":"비트 조정","p_lyrics_t":"가사","p_lyrics_s":"함께","p_hires_t":"하이레즈","p_hires_s":"무손실"},
    "zh-CN": {"offline_t":"离线可用","offline_s":"随处可听 · 无需 Wi-Fi","eq_t":"10 段均衡器","eq_s":"调校每个节拍，增强低音。","organize_t":"整理每一首歌","organize_s":"专辑、歌手、文件夹与歌单","search_t":"秒速搜索","search_s":"歌曲、歌手与专辑瞬间即达","playlist_t":"打造完美歌单","playlist_s":"构建并整理你的收藏","immersive_t":"沉浸式播放","immersive_s":"全屏封面、歌词与操控","p_off_t":"离线","p_off_s":"无信号","p_eq_t":"均衡器","p_eq_s":"每拍可调","p_lyrics_t":"歌词","p_lyrics_s":"跟唱","p_hires_t":"Hi-Res","p_hires_s":"无损"},
    "sv": {"offline_t":"Tillgänglig offline","offline_s":"Lyssna överallt · utan Wi-Fi","eq_t":"10-band Equalizer","eq_s":"Stäm varje beat. Boosta basen.","organize_t":"Organisera varje låt","organize_s":"Album, artister, mappar & spellistor","search_t":"Hitta direkt","search_s":"Låtar, artister & album på en sekund","playlist_t":"Din perfekta spellista","playlist_s":"Samla och organisera dina samlingar","immersive_t":"Fängslande Now Playing","immersive_s":"Helsidesomslag, texter & kontroller","p_off_t":"Offline","p_off_s":"Utan signal","p_eq_t":"Equalizer","p_eq_s":"Varje beat","p_lyrics_t":"Texter","p_lyrics_s":"Mitsjung","p_hires_t":"Hi-Res","p_hires_s":"Förlustfri"},
    "da": {"offline_t":"Tilgængelig offline","offline_s":"Lyt overalt · uden Wi-Fi","eq_t":"10-bånd Equalizer","eq_s":"Stem hver beat. Boost basen.","organize_t":"Organisér hver sang","organize_s":"Albums, kunstnere, mapper & playlister","search_t":"Find med det samme","search_s":"Sange, kunstnere & albums på et sekund","playlist_t":"Din perfekte playlist","playlist_s":"Saml og organisér dine samlinger","immersive_t":"Opslugende Now Playing","immersive_s":"Fuldskærmsomslag, tekster & kontroller","p_off_t":"Offline","p_off_s":"Uden signal","p_eq_t":"Equalizer","p_eq_s":"Hver beat","p_lyrics_t":"Tekster","p_lyrics_s":"Syng med","p_hires_t":"Hi-Res","p_hires_s":"Tabsfri"},
    "no": {"offline_t":"Tilgjengelig offline","offline_s":"Hør overalt · uten Wi-Fi","eq_t":"10-bånd Equalizer","eq_s":"Juster hvert beat. Boost bassen.","organize_t":"Organiser hver sang","organize_s":"Album, artister, mapper & spillelister","search_t":"Finn med én gang","search_s":"Sanger, artister & album på et sekund","playlist_t":"Din perfekte spilleliste","playlist_s":"Samle og organiser samlingene","immersive_t":"Oppslukende Now Playing","immersive_s":"Fullskjermomslag, tekster & kontroller","p_off_t":"Offline","p_off_s":"Uten signal","p_eq_t":"Equalizer","p_eq_s":"Hvert beat","p_lyrics_t":"Tekster","p_lyrics_s":"Syng med","p_hires_t":"Hi-Res","p_hires_s":"Tapsfri"},
    "fi": {"offline_t":"Saatavilla offline","offline_s":"Kuuntele kaikkialla · ilman Wi-Fiä","eq_t":"10-kaistainen taajuuskorjain","eq_s":"Säädä joka isku. Vahvista basso.","organize_t":"Järjestä jokainen kappale","organize_s":"Albumit, artistit, kansiot & soittolistat","search_t":"Löydä heti","search_s":"Kappaleet, artistit & albumit silmänräpäyksessä","playlist_t":"Täydellinen soittolista","playlist_s":"Kokoa ja järjestä kokoelmasi","immersive_t":"Immersiivinen Now Playing","immersive_s":"Kokoruudun kansikuva, sanat & hallinta","p_off_t":"Offline","p_off_s":"Ilman signaalia","p_eq_t":"Taajuusk.","p_eq_s":"Joka isku","p_lyrics_t":"Sanat","p_lyrics_s":"Laule mukana","p_hires_t":"Hi-Res","p_hires_s":"Häviötön"},
    "pl": {"offline_t":"Dostępne offline","offline_s":"Słuchaj wszędzie · bez Wi-Fi","eq_t":"10-pasmowy equalizer","eq_s":"Dostosuj każdy bit. Wzmocnij bas.","organize_t":"Uporządkuj każdą piosenkę","organize_s":"Albumy, artyści, foldery i playlisty","search_t":"Znajdź natychmiast","search_s":"Piosenki, artyści i albumy w mgnieniu","playlist_t":"Twoja idealna playlista","playlist_s":"Twórz i uporządkuj kolekcje","immersive_t":"Pochłaniający odtwarzacz","immersive_s":"Pełnoekranowa okładka, teksty i kontrola","p_off_t":"Offline","p_off_s":"Bez zasięgu","p_eq_t":"Equalizer","p_eq_s":"Każdy bit","p_lyrics_t":"Teksty","p_lyrics_s":"Śpiewaj","p_hires_t":"Hi-Res","p_hires_s":"Bezstratny"},
}

def _c(lang):
    return CALL.get(lang, CALL["en-US"])

def shot1(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("nowplaying")+_callout("airplane",c["offline_t"],c["offline_s"],GREEN,150)
def shot2(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("equalizer")+_callout("sliders",c["eq_t"],c["eq_s"],ROSE,150)
def shot3(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("library")+_callout("folder",c["organize_t"],c["organize_s"],GREEN,150)
def shot4(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("search")+_callout("search",c["search_t"],c["search_s"],ROSE,150)
def shot5(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("home")+_callout("queue",c["playlist_t"],c["playlist_s"],GREEN,150)
def shot6(ui, covers, lang="en-US"):
    c=_c(lang); return _frame("nowplaying")+_callout("quote",c["immersive_t"],c["immersive_s"],ROSE,150)
def shot7(ui, covers, lang="en-US"):
    c=_c(lang)
    return _frame("settings1")+f'<div class="pills" style="bottom:150px">{_pill("airplane",c["p_off_t"],c["p_off_s"],GREEN)}{_pill("sliders",c["p_eq_t"],c["p_eq_s"],ROSE)}</div><div class="pills" style="bottom:300px">{_pill("quote",c["p_lyrics_t"],c["p_lyrics_s"],ROSE)}{_pill("wave",c["p_hires_t"],c["p_hires_s"],GREEN)}</div>'

SHOTS = {1:shot1,2:shot2,3:shot3,4:shot4,5:shot5,6:shot6,7:shot7}
